/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 12:05:23 GMT 2019
 */

package org.pub.whitebox;

import static org.junit.Assert.assertEquals;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleGraph_ESTest extends SimpleGraph_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction(354, 1, 531);
      assertEquals(531, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction(0, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction((-4614), (-4614), (-4614));
      assertEquals((-4614), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction(354, 1368, 1368);
      assertEquals(1368, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction(354, 1368, 354);
      assertEquals(1368, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = SimpleGraph.simpleFunction(1368, 1368, 1368);
      assertEquals(1368, int0);
  }
}
